spring.application.name=labb-1-integration-mot-google-gemini


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=lab_1_integration_mot_google_gemini
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.mvc.hiddenmethod.filter.enabled=true








