spring.application.name=labb-1-integration-mot-google-gemini


#database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.hiddenmethod.filter.enabled=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.default_schema=lab_1_integration_mot_google_gemini





#google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

GOOGLE_API_KEY=${GEMINI_API_KEY}
gemini.model=gemini-3-flash-preview



# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# logging
logging.level.se.iths.lw.labb1integrationmotgooglegemini=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

