spring.application.name=labb-1-integration-mot-google-gemini


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.default_schema=lab_1_integration_mot_google_gemini
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.mvc.hiddenmethod.filter.enabled=true





spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
GOOGLE_API_KEY=${GEMINI_API_KEY}
gemini.model=gemini-3-flash-preview



# Thymeleaf 配置（确保模板正确渲染）
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# 日志级别（便于调试）
logging.level.se.iths.lw.labb1integrationmotgooglegemini=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

